
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py
  labels:
    app: hello-py
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-py
  template: 
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - name: hello-py
        image: localhost:5000/hello-py:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: hello-py-ext
  namespace: kube-system
spec:
  type: ExternalName
  externalName: hello-py.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-py
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8181
      protocol: TCP
  type: NodePort
  selector:
    app: hello-py